name: 'add-github-ssh-key'
description: 'Adds your github ssh keys to the correct destination'
author: 'seemethere'
inputs:
  GITHUB_TOKEN:
    required: true
  activate-with-label:
    required: true
    description: 'Tells the action only to add keys when specific label is applied, set false if you want the key to always be added'
    default: true
  label:
    required: true
    description: 'Label to activate action with'
    default: 'with-ssh'
  remove-existing-keys:
    required: true
    description: 'Removes existing keys at ~/.ssh/authorized_keys before adding new ones'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
