name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn run all
  test-linux: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Check if can write keys
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          activate-with-label: false
      - uses: ./
        name: Check if can overwrite keys
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          activate-with-label: false
      - name: Check SSH key is there
        if: (github.event_name == 'pull_request')
        run: |
          test -e ~/.ssh/authorized_keys
          # Check that file contents match, strip trailing newline from curl call
          diff \
            <(curl -fsSL "https://github.com/${{ github.actor}}.keys" | sed -z '$ s/\n$//') \
            ~/.ssh/authorized_keys
      - name: Check SSH key is not there
        if: (github.event_name == 'push')
        run: |
          # Check that file does not exist for push
          test -e ~/.ssh/authorized_keys || exit 0
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Check if can write keys
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          activate-with-label: false
      - uses: ./
        name: Check if can overwrite keys
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          activate-with-label: false
